#!/usr/bin/env python3
"""Generate finite PPC multiply boundary literals from exact rational arithmetic.

Run from any directory; writes the include consumed by core and sanitizer tests.
"""
from pathlib import Path
from fractions import Fraction

def value(raw):
 b=raw>>52; f=raw&((1<<52)-1); return Fraction(f|(1<<52) if b else f)*Fraction(2)**(b-1023-52 if b else -1074)
def power(e):return Fraction(2)**e
def floorlog(x):
 e=x.numerator.bit_length()-x.denominator.bit_length()
 return e if x>=power(e) else e-1
def encode(x):
 if not x:return 0
 e=floorlog(x)
 if e < -1022: return int(x/power(-1074))
 assert -1022<=e<=1023
 f=int((x/power(e)-1)*power(52)); assert x==(1+Fraction(f,1<<52))*power(e)
 return ((e+1023)<<52)|f

def rounded(a,b,precision,rn,enabled):
 x=value(a)*value(b);p=24 if precision==59 else 53;lo=-126 if precision==59 else -1022;hi=127 if precision==59 else 1023
 if not x:return 0,0,False
 e=floorlog(x);tiny=e<lo;unit=(lo if tiny and not enabled else e)-(p-1)
 q=x/power(unit); n,rem=divmod(q.numerator,q.denominator)
 inc=bool(rem) and (rn==2 or rn==0 and (rem*2>q.denominator or rem*2==q.denominator and n%2))
 n+=inc;y=n*power(unit);overflow=bool(y) and floorlog(y)>hi
 flags=(1 if rem else 0)|(2 if inc else 0)|(4 if tiny and (enabled or rem) else 0)|(8 if overflow else 0)
 if overflow and not enabled:
  flags=(flags&~2)|1
  return (0x7ff0000000000000 if rn in (0,2) else encode((2-power(1-p))*power(hi))),flags,tiny
 if enabled:y*=power((192 if precision==59 else 1536) if tiny else -(192 if precision==59 else 1536) if overflow else 0)
 return encode(y),flags,tiny
# Independent exact rational table; no reference or native implementation is used.
double=[(0,0x3ff0000000000000),(0x3ff0000000000000,0x4000000000000000),
(0x3ff0000000000001,0x3ff0000000000001),(0x3ff0000000000001,0x3fffffffffffffff),
(0x3fffffffffffffff,0x3fffffffffffffff),(0x3ff8000000000000,0x3ff0000000000001),
(0x3ff8000000000001,0x3ff8000000000000),(0x3ff0000000000001,0x3ff8000000000001),
(0x3fe0000000000000,0x0010000000000000),(0x3fe0000000000001,0x0010000000000000),
(0x0010000000000000,0x0010000000000000),(1,1),(3,0x3fe0000000000000),
(1,0x3fe0000000000000),(1,0x3fe0000000000001),(1,0x3fdfffffffffffff),
(0x000fffffffffffff,0x3ff0000000000000),(0x0010000000000000,0x3fefffffffffffff),
(0x0010000000000001,0x3fefffffffffffff),(0x7fefffffffffffff,0x4000000000000000),
(0x7fefffffffffffff,0x3ff0000000000001),(0x7fefffffffffffff,0x7fefffffffffffff),
(0x7fe0000000000000,0x4000000000000000),(0x0010000000000000,0x7fefffffffffffff),
(1,0x7fefffffffffffff),(0x3ff0000000000000,1)]
single=[(0,0x3ff0000000000000),(0x3ff0000000000000,0x4000000000000000),
(0x3ff0000020000000,0x3ff0000020000000),(0x3ffffffff0000000,0x3ffffffff0000000),
(0x3ff8000000000000,0x3ff0000020000000),(0x3ff8000020000000,0x3ff8000000000000),
(0x3810000000000000,0x3fe0000000000000),(0x3810000000000000,0x3fe0000020000000),
(0x3810000000000000,0x3fefffffe0000000),(0x3810000020000000,0x3fefffffe0000000),
(0x36a0000000000000,0x3fe0000000000000),(0x36a0000000000000,0x3fe0000020000000),
(0x36a0000000000000,0x3fdfffffe0000000),(0x36b8000000000000,0x3fe0000000000000),
(0x36a0000000000000,0x36a0000000000000),(0x3810000000000000,0x3810000000000000),
(0x380fffffc0000000,0x3ff0000000000000),(0x47efffffe0000000,0x4000000000000000),
(0x47efffffe0000000,0x3ff0000020000000),(0x47efffffe0000000,0x47efffffe0000000),
(0x47e0000000000000,0x4000000000000000),(0x36a0000000000000,0x47efffffe0000000)]
# Correct the largest-single representation (the preceding neighbor's low bit was malformed).
single=[(a if a!=0x3ffffffff0000000 else 0x3fffffffe0000000,b if b!=0x3ffffffff0000000 else 0x3fffffffe0000000) for a,b in single]
import random
rng=random.Random(0x50504336)
for precision, corpus in ((59,single),(63,double)):
 for i in range(24):
  exponents=(-126,-125,-1,0,1,126,127) if precision==59 else (-1022,-1021,-1,0,1,1022,1023)
  if precision==59:
   a=((rng.choice(exponents)+1023)<<52)|(rng.getrandbits(23)<<29)
   b=((rng.choice(exponents)+1023)<<52)|(rng.getrandbits(23)<<29)
  else:
   a=((rng.choice(exponents)+1023)<<52)|rng.getrandbits(52)
   b=((rng.choice(exponents)+1023)<<52)|rng.getrandbits(52)
  corpus.append((a,b))
rows=[]
for precision,inputs in ((59,single),(63,double)):
 for a,b in inputs:
  x=[rounded(a,b,precision,r,False) for r in range(4)];y=[rounded(a,b,precision,r,True) for r in range(4)]
  arr=lambda z:'{'+','.join(f'0x{v:016x}ULL' for v in z)+'}'
  flags=lambda z:'{'+','.join(str(v) for v in z)+'}'
  rows.append(f'        {{{precision},0x{a:016x}ULL,0x{b:016x}ULL,{str(x[0][2]).lower()},{arr(v[0] for v in x)},{flags(v[1] for v in x)},{arr(v[0] for v in y)},{flags(v[1] for v in y)}}},')

root=Path(__file__).resolve().parents[1]
path=root/'SheepShaver/src/kpx_cpu/tests/ppc_multiply_literals.inc'
path.write_text('// Generated by tools/gen_ppc_multiply_literals.py using Fraction.\n'+ '\n'.join(rows)+'\n')
print(f'wrote {path}: {len(rows)} exact-product literals')
